In [72]:
import matplotlib.pyplot as plt
%matplotlib inline
import pandas as pd
import numpy as np
from scipy import stats
import pylab

In [73]:
# Load up codebook
pc = pd.DataFrame.from_csv('cap-data/recs2009_public_codebook_simple.csv', index_col= None, encoding = 'utf-8')

In [74]:
# Separate response codes and labels
pc['Response Codes']=[x.split('\r') if type(x) == str else x for x in pc['Response Codes']]
pc['Response Labels']=[x.split('\r') if type(x) == str else x for x in pc['Response Labels']]
pc = pc.ix[:930] # last 3 lines unnecessary
pc.tail()

,Variable Name,Variable Description,Response Codes,Response Labels,Electricity,Natural Gas,Propane,Fuel Oil,Kerosene
926,SCALELP,Whether annualized LPG/propane consumption fro...,"[0, 1, , 2, , 3, -2]","[Not scaled down, Scaled down because billing ...",NaN,NaN,NaN,NaN,NaN
927,PERIODFO,Number of days covered by Energy Supplier Surv...,"[1, 2, 5, -2]","[365 days (complete), Less than 365 days (inco...",NaN,NaN,NaN,NaN,NaN
928,SCALEFO,Whether annualized fuel oil consumption from E...,"[0, 1, , 2, , 3, -2]","[Not scaled down, Scaled down because billing ...",NaN,NaN,NaN,NaN,NaN
929,PERIODKR,Number of days covered by Energy Supplier Surv...,"[1, 2, 5, -2]","[365 days (complete), Less than 365 days (inco...",NaN,NaN,NaN,NaN,NaN
930,SCALEKER,Whether annualized kerosene consumption from E...,"[0, 1, , 2, , 3, -2]","[Not scaled down, Scaled down because billing ...",NaN,NaN,NaN,NaN,NaN

In [75]:
# Imputations are the EIA's guesses at filling in blank forms. Since blanks are few, imputation will be ignored.
no_imp = pc[pc['Variable Description'].str.contains('Imputation flag for') != True]
no_imp.head()

,Variable Name,Variable Description,Response Codes,Response Labels,Electricity,Natural Gas,Propane,Fuel Oil,Kerosene
0,DOEID,Unique identifier for each respondent,[00001 - 12083],[Unique identifier for each respondent],NaN,NaN,NaN,NaN,NaN
1,REGIONC,Census Region,"[1, 2, 3, 4]","[Northeast Census Region, Midwest Census Regio...",NaN,NaN,NaN,NaN,NaN
2,DIVISION,Census Division,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]","[New England Census Division (CT, MA, ME, NH, ...",NaN,NaN,NaN,NaN,NaN
3,REPORTABLE_DOMAIN,Reportable states and groups of states,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...","[, Connecticut, Maine, New Hampshire, Rhode Is...",NaN,NaN,NaN,NaN,NaN
4,TYPEHUQ,Type of housing unit,"[1, 2, 3, 4, 5]","[Mobile Home, Single-Family Detached, Single-F...",OTH_B,SPH_A,NaN,NaN,NaN

In [98]:
# Separate numeric responses
num_resp = no_imp[no_imp['Response Codes'].isnull() == True]
num_resp

,Variable Name,Variable Description,Response Codes,Response Labels,Electricity,Natural Gas,Propane,Fuel Oil,Kerosene
5,NWEIGHT,Final sample weight,NaN,[Final sample weight],NaN,NaN,NaN,NaN,NaN
6,HDD65,"Heating degree days in 2009, base temperature 65F",NaN,"[Heating degree days in 2009, base temperature...","SPH_B, WTH_A",SPH_B,"SPH_B, OTH_B","SPH_B, OTH_B","SPH_B, OTH_B"
7,CDD65,"Cooling degree days in 2009, base temperature 65F",NaN,"[Cooling degree days in 2009, base temperature...",COL_B,NaN,NaN,NaN,NaN
8,HDD30YR,"Heating degree days, 30-year average 1981-2010...",NaN,"[Heating degree days, 30-year average 1981-201...",NaN,NaN,NaN,NaN,NaN
9,CDD30YR,"Cooling degree days, 30-year average 1981-2010...",NaN,"[Cooling degree days, 30-year average 1981-201...",NaN,NaN,NaN,NaN,NaN
827,TOTSQFT,Total square footage (includes all attached ga...,NaN,[Square Feet],NaN,NaN,NaN,NaN,NaN
828,TOTSQFT_EN,Total square footage (includes heated/cooled g...,NaN,[Square Feet],OTH_B,NaN,NaN,NaN,NaN
829,TOTHSQFT,Total heated square footage,NaN,[Square Feet],SPH_B,SPH_B,"SPH_B, OTH_B","SPH_B, OTH_B","SPH_B, WTH_B, OTH_B"
830,TOTUSQFT,Total unheated square footage,NaN,[Square Feet],NaN,NaN,NaN,NaN,NaN
831,TOTCSQFT,Total cooled square footage,NaN,[Square Feet],NaN,NaN,NaN,NaN,NaN
832,TOTUCSQFT,Total uncooled square footage,NaN,[Square Feet],COL_B,NaN,NaN,NaN,NaN
839,KWH,"Total Site Electricity usage, in kilowatt-hour...",NaN,[Kilowatt-hours],NaN,NaN,NaN,NaN,NaN
840,KWHSPH,"Electricity usage for space heating, in kilowa...",NaN,[Kilowatt-hours],NaN,NaN,NaN,NaN,NaN
841,KWHCOL,"Electricity usage for air-conditioning, centra...",NaN,[Kilowatt-hours],NaN,NaN,NaN,NaN,NaN
842,KWHWTH,"Electricity usage for water heating, in kilowa...",NaN,[Kilowatt-hours],NaN,NaN,NaN,NaN,NaN
843,KWHRFG,"Electricity usage for refrigerators, in kilowa...",NaN,[Kilowatt-hours],NaN,NaN,NaN,NaN,NaN
844,KWHOTH,Electricity usage for other purposes (all end-...,NaN,[Kilowatt-hours],NaN,NaN,NaN,NaN,NaN
845,BTUEL,"Total Site Electricity usage, in thousand BTU,...",NaN,[Thousand BTU],NaN,NaN,NaN,NaN,NaN
846,BTUELSPH,"Electricity usage for space heating, in thousa...",NaN,[Thousand BTU],NaN,NaN,NaN,NaN,NaN
847,BTUELCOL,"Electricity usage for air-conditioning, centra...",NaN,[Thousand BTU],NaN,NaN,NaN,NaN,NaN
848,BTUELWTH,"Electricity usage for water heating, in thousa...",NaN,[Thousand BTU],NaN,NaN,NaN,NaN,NaN
849,BTUELRFG,"Electricity usage for refrigerators, in thousa...",NaN,[Thousand BTU],NaN,NaN,NaN,NaN,NaN
850,BTUELOTH,Electricity usage for other purposes (all end-...,NaN,[Thousand BTU],NaN,NaN,NaN,NaN,NaN
851,DOLLAREL,"Total Electricity cost, in whole dollars, 2009",NaN,[Dollars],NaN,NaN,NaN,NaN,NaN
852,DOLELSPH,"Electricity cost for space heating, in whole d...",NaN,[Dollars],NaN,NaN,NaN,NaN,NaN
853,DOLELCOL,"Electricity cost for air-conditioning, central...",NaN,[Dollars],NaN,NaN,NaN,NaN,NaN
854,DOLELWTH,"Electricity cost for water heating, in whole d...",NaN,[Dollars],NaN,NaN,NaN,NaN,NaN
855,DOLELRFG,"Electricity cost for refrigerators, in whole d...",NaN,[Dollars],NaN,NaN,NaN,NaN,NaN
856,DOLELOTH,Electricity cost for other purposes (all end-u...,NaN,[Dollars],NaN,NaN,NaN,NaN,NaN
857,CUFEETNG,"Total Natural Gas usage, in hundred cubic feet...",NaN,[Hundred cubic feet of natural gas],NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
889,DOLLARFO,"Total cost of Fuel Oil, in whole dollars, 2009",NaN,[Dollars],NaN,NaN,NaN,NaN,NaN
890,DOLFOSPH,"Cost of Fuel Oil for space heating, in whole d...",NaN,[Dollars],NaN,NaN,NaN,NaN,NaN
891,DOLFOWTH,"Cost of Fuel Oil for water heating, in whole d...",NaN,[Dollars],NaN,NaN,NaN,NaN,NaN
892,DOLFOOTH,Cost of Fuel Oil for other purposes (all end-u...,NaN,[Dollars],NaN,NaN,NaN,NaN,NaN
893,GALLONKER,"Total Kerosene usage, in gallons, 2009",NaN,[Gallons of kerosene],NaN,NaN,NaN,NaN,NaN
894,GALLONKERSPH,"Kerosene usage for space heating, in gallons, ...",NaN,[Gallons of kerosene],NaN,NaN,NaN,NaN,NaN
895,GALLONKERWTH,"Kerosene usage for water heating, in gallons, ...",NaN,[Gallons of kerosene],NaN,NaN,NaN,NaN,NaN
896,GALLONKEROTH,Kerosene usage for other purposes (all end-use...,NaN,[Gallons of kerosene],NaN,NaN,NaN,NaN,NaN
897,BTUKER,"Total Kerosene usage, in thousand BTU, 2009",NaN,[Thousand BTU],NaN,NaN,NaN,NaN,NaN
898,BTUKERSPH,"Kerosene usage for space heating, in thousand ...",NaN,[Thousand BTU],NaN,NaN,NaN,NaN,NaN
899,BTUKERWTH,"Kerosene usage for water heating, in thousand ...",NaN,[Thousand BTU],NaN,NaN,NaN,NaN,NaN
900,BTUKEROTH,Kerosene usage for other purposes (all end-use...,NaN,[Thousand BTU],NaN,NaN,NaN,NaN,NaN
901,DOLLARKER,"Total cost of Kerosene, in whole dollars, 2009",NaN,[Dollars],NaN,NaN,NaN,NaN,NaN
902,DOLKERSPH,"Cost of Kerosene for space heating, in whole d...",NaN,[Dollars],NaN,NaN,NaN,NaN,NaN
903,DOLKERWTH,"Cost of Kerosene for water heating, in whole d...",NaN,[Dollars],NaN,NaN,NaN,NaN,NaN
904,DOLKEROTH,Cost of Kerosene for other purposes (all end-u...,NaN,[Dollars],NaN,NaN,NaN,NaN,NaN
905,BTUWOOD,"Total Wood usage, in thousand BTU, 2009 (Wood ...",NaN,[Thousand BTU],NaN,NaN,NaN,NaN,NaN
906,CORDSWD,"Total Wood usage, in cords, 2009 (Wood consump...",NaN,[Cords of wood],NaN,NaN,NaN,NaN,NaN
907,TOTALBTU,"Total usage, in thousand BTU, 2009",NaN,[Thousand BTU],NaN,NaN,NaN,NaN,NaN
908,TOTALBTUSPH,"Total usage for space heating, in thousand BTU...",NaN,[Thousand BTU],NaN,NaN,NaN,NaN,NaN
909,TOTALBTUCOL,"Total usage for air conditioning, in thousand ...",NaN,[Thousand BTU],NaN,NaN,NaN,NaN,NaN
910,TOTALBTUWTH,"Total usage for water heating, in thousand BTU...",NaN,[Thousand BTU],NaN,NaN,NaN,NaN,NaN
911,TOTALBTURFG,"Total usage for refrigerators, in thousand BTU...",NaN,[Thousand BTU],NaN,NaN,NaN,NaN,NaN
912,TOTALBTUOTH,"Total usage for appliances, electronics, light...",NaN,[Thousand BTU],NaN,NaN,NaN,NaN,NaN
913,TOTALDOL,"Total cost, in whole dollars, 2009",NaN,[Dollars],NaN,NaN,NaN,NaN,NaN
914,TOTALDOLSPH,"Total cost for space heating, in whole dollars...",NaN,[Dollars],NaN,NaN,NaN,NaN,NaN
915,TOTALDOLCOL,"Total cost for air conditioning, in whole doll...",NaN,[Dollars],NaN,NaN,NaN,NaN,NaN
916,TOTALDOLWTH,"Total cost for water heating, in whole dollars...",NaN,[Dollars],NaN,NaN,NaN,NaN,NaN
917,TOTALDOLRFG,"Total cost for refrigerators, in whole dollars...",NaN,[Dollars],NaN,NaN,NaN,NaN,NaN
918,TOTALDOLOTH,"Total cost for appliances, electronics, lighti...",NaN,[Dollars],NaN,NaN,NaN,NaN,NaN

In [99]:
# Separate categorical responses
cat_resp = no_imp[no_imp['Response Codes'].isnull() == False]
cat_resp

,Variable Name,Variable Description,Response Codes,Response Labels,Electricity,Natural Gas,Propane,Fuel Oil,Kerosene
0,DOEID,Unique identifier for each respondent,[00001 - 12083],[Unique identifier for each respondent],NaN,NaN,NaN,NaN,NaN
1,REGIONC,Census Region,"[1, 2, 3, 4]","[Northeast Census Region, Midwest Census Regio...",NaN,NaN,NaN,NaN,NaN
2,DIVISION,Census Division,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]","[New England Census Division (CT, MA, ME, NH, ...",NaN,NaN,NaN,NaN,NaN
3,REPORTABLE_DOMAIN,Reportable states and groups of states,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...","[, Connecticut, Maine, New Hampshire, Rhode Is...",NaN,NaN,NaN,NaN,NaN
4,TYPEHUQ,Type of housing unit,"[1, 2, 3, 4, 5]","[Mobile Home, Single-Family Detached, Single-F...",OTH_B,SPH_A,NaN,NaN,NaN
10,Climate_Region_Pub,Building America Climate Region (collapsed for...,"[1, 2, 3, 4, 5]","[Very Cold/Cold, Hot-Dry/Mixed-Dry, Hot-Humid,...",NaN,NaN,NaN,NaN,NaN
11,AIA_Zone,"AIA Climate Zone, based on average temperature...","[1, 2, 3, 4, 5]","[Less than 2,000 CDD and greater than 7,000 HD...",SPH_A,SPH_A,NaN,NaN,NaN
12,METROMICRO,Housing unit in Census Metropolitan Statistica...,"[METRO, MICRO, NONE]",[Housing unit in Census Metropolitan Statistic...,NaN,NaN,NaN,NaN,NaN
13,UR,Housing unit classified as urban or rural by C...,"[U, R]","[Urban, Rural]",NaN,NaN,NaN,NaN,NaN
14,KOWNRENT,"Housing unit is owned, rented, or occupied wit...","[1, 2, 3]","[Owned by someone in the household, Rented, Oc...",NaN,NaN,NaN,NaN,NaN
15,CONDCOOP,Housing unit part of condominium or cooperative,"[1, 2, -2]","[Condominium, Cooperative, Not Applicable]",NaN,NaN,NaN,NaN,NaN
16,YEARMADE,Year housing unit was built,[1600 - 2009],[Year housing unit was built],NaN,NaN,NaN,NaN,NaN
17,YEARMADERANGE,Year range when housing unit was built,"[1, 2, 3, 4, 5, 6, 7, 8]","[Before 1950, 1950 to 1959, 1960 to 1969, 1970...",NaN,SPH_A,SPH_A,SPH_A,NaN
18,OCCUPYYRANGE,Year range when household moved in,"[1, 2, 3, 4, 5, 6, 7, 8]","[Before 1950, 1950 to 1959, 1960 to 1969, 1970...",NaN,NaN,NaN,NaN,NaN
19,CONVERSION,Converted 2-4 unit apartment building,"[1, 2, -2]","[Built as an apartment building, Converted int...",NaN,NaN,NaN,NaN,NaN
20,ORIG1FAM,Converted 2-4 unit apartment building was orig...,"[0, 1, -2]","[No, Yes, Not Applicable]",NaN,NaN,NaN,NaN,NaN
21,LOOKLIKE,Converted 2-4 unit apartment building more lik...,"[1, 2, -2]","[More like a single-family house, More like an...",NaN,NaN,NaN,NaN,NaN
22,NUMFLRS,Number of floors in a 5+ unit apartment building,"[1 - 99, -2]","[Number of floors, Not Applicable]",NaN,NaN,NaN,NaN,NaN
23,NUMAPTS,Number of apartment units in a 5+ unit apartme...,"[5 - 995, -2]","[Number of apartment units, Not Applicable]",NaN,NaN,NaN,NaN,NaN
24,WALLTYPE,Major outside wall material,"[1, 2, 3, 4, 5, 6, 7, 8, 9]","[Brick, Wood, Siding (Aluminum, Vinyl, Steel),...",NaN,NaN,NaN,NaN,NaN
25,ROOFTYPE,Major roofing material,"[1, 2, 3, 4, 5, 6, 7, 8, -2]","[Ceramic or Clay Tiles, Wood Shingles/Shakes, ...",NaN,NaN,NaN,NaN,NaN
26,STUDIO,Studio apartment,"[0, 1, -2]","[No, Yes, Not Applicable]",NaN,NaN,NaN,NaN,NaN
27,NAPTFLRS,Number of floors in an apartment (Number of le...,"[1 - 9, -2]","[Number of floors in apartment, Not Applicable]",NaN,NaN,NaN,NaN,NaN
28,STORIES,Number of stories in a single-family home,"[10, 20, 31, 32, 40, 50, -2]","[One story, Two stories, Three stories, Four o...",NaN,NaN,NaN,NaN,NaN
29,TYPEHUQ4,Addition to a mobile home,"[0, 1, -2]","[No, Yes, Not Applicable]",NaN,NaN,NaN,NaN,NaN
30,BEDROOMS,Number of bedrooms,"[0 - 20, -2]","[Number of bedrooms, Not Applicable]",NaN,NaN,NaN,NaN,NaN
31,NCOMBATH,Number of full bathrooms,[0 - 9],[Number of full bathrooms],NaN,NaN,NaN,NaN,NaN
32,NHAFBATH,Number of half bathrooms,[0 - 9],[Number of half bathrooms],NaN,NaN,NaN,NaN,NaN
33,OTHROOMS,Number of rooms other than bedroom(s) and bath...,[1 - 20],[Number of other rooms],NaN,NaN,NaN,NaN,NaN
34,TOTROOMS,Total number of rooms in the housing unit,[1 - 25],[Total number of rooms in the housing unit],COL_B,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
773,AGEHHMEMCAT14,Age category of fourteenth household member,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...","[< 5 years old, 5-9 years old, 10-14 years old...",NaN,NaN,NaN,NaN,NaN
774,HBUSNESS,Home-based business or service,"[0, 1]","[No, Yes]",NaN,NaN,NaN,NaN,NaN
775,ATHOME,Household member at home on typical week days,"[0, 1]","[No, Yes]",NaN,NaN,NaN,NaN,NaN
776,TELLWORK,Household member(s) telecommutes or teleworks,"[0, 1]","[No, Yes]",NaN,NaN,NaN,NaN,NaN
777,TELLDAYS,Number of telecommuting days per month,"[1 - 31, -2]","[Number of Telecommuting Days, Not Applicable]",NaN,NaN,NaN,NaN,NaN
778,OTHWORK,Any activities that use an unusual amount of e...,"[0, 1]","[No, Yes]",NaN,NaN,NaN,NaN,NaN
779,WORKPAY,Household members received employment income i...,"[0, 1]","[No, Yes]",NaN,NaN,NaN,NaN,NaN
780,RETIREPY,Household members received retirement income i...,"[0, 1]","[No, Yes]",NaN,NaN,NaN,NaN,NaN
781,SSINCOME,Household members received Supplemental Securi...,"[0, 1]","[No, Yes]",NaN,NaN,NaN,NaN,NaN
782,CASHBEN,Household members received welfare payments or...,"[0, 1]","[No, Yes]",NaN,NaN,NaN,NaN,NaN
783,INVESTMT,Household members received investment income i...,"[0, 1]","[No, Yes]",NaN,NaN,NaN,NaN,NaN
784,RGLRPAY,Household members received other regular incom...,"[0, 1]","[No, Yes]",NaN,NaN,NaN,NaN,NaN
785,MONEYPY,2009 gross household income,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...","[Less than $2,500, $2,500 to $4,999, $5,000 to...",NaN,OTH_A,NaN,NaN,NaN
786,POVERTY100,Household income at or below 100% of poverty line,"[0, 1]","[No, Yes]",NaN,NaN,NaN,NaN,NaN
787,POVERTY150,Household income at or below 150% of poverty line,"[0, 1]","[No, Yes]",NaN,NaN,NaN,NaN,NaN
788,HUPROJ,Housing unit in public housing authority,"[0, 1, -2]","[No, Yes, Not Applicable]",NaN,NaN,NaN,NaN,NaN
789,RENTHELP,"Lower rent due to Federal, State, or Local hou...","[0, 1, -2]","[No, Yes, Not Applicable]",NaN,NaN,NaN,NaN,NaN
790,FOODASST,Household receives food stamps or WIC assistance,"[0, 1]","[No, Yes]",NaN,NaN,NaN,NaN,NaN
919,KAVALEL,Electricity end uses included in Energy Suppli...,"[1, 2, , 3]",[All end uses applicable to housing unit inclu...,NaN,NaN,NaN,NaN,NaN
920,PERIODEL,Number of days covered by Energy Supplier Surv...,"[1, 2, 3, 4, 5]","[330 days or more, At least 146, but less than...",NaN,NaN,NaN,NaN,NaN
921,SCALEEL,Whether annualized electricity consumption fro...,"[0, 1, , 2, , 3]","[Not scaled down, Scaled down because billing ...",NaN,NaN,NaN,NaN,NaN
922,KAVALNG,Natural gas end uses included in Energy Suppli...,"[1, 2, , 3, -2]",[All end uses applicable to housing unit inclu...,NaN,NaN,NaN,NaN,NaN
923,PERIODNG,Number of days covered by Energy Supplier Surv...,"[1, 2, 3, 4, 5, -2]","[330 days or more, At least 146, but less than...",NaN,NaN,NaN,NaN,NaN
924,SCALENG,Whether annualized natural gas consumption fro...,"[0, 1, , 2, , 3, -2]","[Not scaled down, Scaled down because billing ...",NaN,NaN,NaN,NaN,NaN
925,PERIODLP,Number of days covered by Energy Supplier Surv...,"[1, 2, 5, -2]","[365 days (complete), Less than 365 days (inco...",NaN,NaN,NaN,NaN,NaN
926,SCALELP,Whether annualized LPG/propane consumption fro...,"[0, 1, , 2, , 3, -2]","[Not scaled down, Scaled down because billing ...",NaN,NaN,NaN,NaN,NaN
927,PERIODFO,Number of days covered by Energy Supplier Surv...,"[1, 2, 5, -2]","[365 days (complete), Less than 365 days (inco...",NaN,NaN,NaN,NaN,NaN
928,SCALEFO,Whether annualized fuel oil consumption from E...,"[0, 1, , 2, , 3, -2]","[Not scaled down, Scaled down because billing ...",NaN,NaN,NaN,NaN,NaN
929,PERIODKR,Number of days covered by Energy Supplier Surv...,"[1, 2, 5, -2]","[365 days (complete), Less than 365 days (inco...",NaN,NaN,NaN,NaN,NaN
930,SCALEKER,Whether annualized kerosene consumption from E...,"[0, 1, , 2, , 3, -2]","[Not scaled down, Scaled down because billing ...",NaN,NaN,NaN,NaN,NaN

In [107]:
cat_resp['Response Codes'][928][2]

''